[package]
name = "deviz"
version = "0.1.3"
authors = ["Brandon Pickering"]
edition = "2018"
license = "MIT"
description = "Provides access to a VS Code extension for displaying structured program output"
repository = "https://github.com/branpk/deviz"

[dependencies]
json = "0.12.4"
