[package]
name = "deviz"
version = "0.1.0"
authors = ["Brandon Pickering <brandonpickering95@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.60"
